# Generated by Django 2.2.5 on 2019-09-25 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lime', '0002_auto_20190920_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lime.Category', verbose_name='coco'),
        ),
    ]
