# Generated by Django 2.2.5 on 2019-09-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lime', '0004_auto_20190926_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.TextField(max_length=200),
        ),
    ]
