# Generated by Django 2.2.5 on 2019-09-26 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lime', '0005_auto_20190926_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='subject',
            new_name='content',
        ),
    ]
