# Generated by Django 2.2.5 on 2019-09-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lime', '0006_auto_20190926_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
