# Generated by Django 2.2.5 on 2019-09-26 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lime', '0007_auto_20190926_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje', to='lime.Category'),
        ),
    ]
